name: Bug Report
description: Thanks for the report!
title: "[BUG]: "
labels: ["bug", "triage"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Laerdal SimServer Imager are you running? (Run with --version to check)
      placeholder: ex 1.0.0
    validations:
      required: true
  - type: dropdown
    id: host-os
    attributes:
      label: What host operating system were you using?
      multiple: false
      options:
        - Windows
        - macOS
        - Debian and derivatives (eg Ubuntu)
        - Other Linux environment
        - Other non-Linux environment
    validations:
      required: true
  - type: input
    id: host-os-version
    attributes:
      label: Host OS Version
      description: What version of your host OS were you using?
      placeholder: ex 11H2, 10.4, Catalina, 22.04
    validations:
      required: true
  - type: input
    id: target-os-version
    attributes:
      label: Selected OS
      description: Which OS did you select to write? (For custom images, just write 'Custom')
      placeholder: ex SimServer OS, Custom Image
    validations:
      required: true
  - type: dropdown
    id: laerdal-device
    attributes:
      label: Which Laerdal Device are you using?
      multiple: false
      options:
        - SimPad PLUS
        - SimMan 3G
        - SimMan Essential
        - SimMan ALS
        - Other Laerdal Device
        - N/A (Testing only)
    validations:
      required: true
  - type: dropdown
    id: storage-device
    attributes:
      label: What kind of storage device are you using?
      multiple: false
      options:
        - microSD Card in an internal reader
        - microSD Card in a USB reader
        - Integrated eMMC
        - USB Pen Drive
        - USB SSD
        - Other
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: OS Customisation
      description: Were you using OS Customisation when you encountered the bug?
      options:
        - label: Yes, I was using OS Customisation when the bug occurred.
          required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
