#!/usr/bin/dh-exec

[amd64] laerdal-simserver-imager-cli-x86_64.AppImage => /usr/bin/laerdal-simserver-imager-cli
[arm64] laerdal-simserver-imager-cli-aarch64.AppImage => /usr/bin/laerdal-simserver-imager-cli
[armhf] laerdal-simserver-imager-cli-armhf.AppImage => /usr/bin/laerdal-simserver-imager-cli

src/linux/icon/laerdal-simserver-imager.svg /usr/share/icons/hicolor/scalable/apps/

debian/com.laerdal.simserver-imager-cli.desktop /usr/share/applications/
